site_name: SIGS

nav:
  - Home: index.md
  - Contribute: contribute.md
  - Stylesheet:
    - Ruby: stylesheet/ruby.md
    - Css: stylesheet/css.md
  - Contributors: contributors.md
  - Planejamento da Release: Planejamento-da-Release.md
  - Gerenciamento do Projeto:
    - Metodologia: Metodologia.md
    - Backlog do Produto: Backlog-do-Produto 
    - Roadmap: Planejamento-da-Release#3-roadmap.md
    - Glossário: Glossario.md
    - Termo de Abertura do Projeto: Termo-de-Abertura-do-Projeto.md
    - Planos PMBOK: Plano-de-Projeto---PMBOK.md
    - Gerenciamento de Projeto: Plano-de-Gerenciamento-de-Projeto.md
    - Gerenciamento de Escopo: Plano-de-Gerenciamento-de-Escopo.md
    - Estrutura Analitica Do Projeto: estrutura-analitica-do-projeto.md
    - Gerenciamento de Cronograma: Plano-de-Gerenciamento-de-Cronograma.md
    - Gerenciamento de Riscos: Plano-de-Gerenciamento-de-Riscos.md
    - Gerenciamento de Aquisições: Plano-de-Gerenciamento-de-Aquisicoes.md
    - Gerenciamento de Comunicação: Plano-de-Gerenciamento-de-Comunicacao.md
    - Gerenciamento de Configuração de Software: Plano-de-Gerenciamento-de-Configuracao-de-Software.md
    - Gerenciamento de Qualidade: Plano-de-Gerenciamento-de-Qualidade.md
    - Plano GQM: Plano-GQM.md 
    - Gerenciamento das Partes Interessadas: Plano-de-Gerenciamento-de-Partes-Interessadas.md
    - Gerenciamento de Requisitos: Plano-de-Gerenciamento-de-Requisitos.md
    - Controle das Mudanças: controle-das-mudancas.md
    - Coleta Métricas: Execucao-do-Plano-de-Qualidade.md
  - Desenvolvimento do Software:
    - Documento de Visão: documento-de-visao.md
    - Documento de Arquitetura: Documento-de-Arquitetura.md
    - Diagrama de Casos de uso: Diagrama-de-Casos-de-Uso.md
    - Modelo de Domínio: Modelo-de-Domínio.md
    - Diagrama de Classes: Diagrama-de-Classe.md
    - Especificação dos Casos de Uso: especificacao-dos-casos-de-uso.md
    - Especificação dos Casos de Teste: especificacao-dos-casos-de-teste.md
    - Especificação Suplementar: especificacao-suplementar.md
    - Protótipo de Alta Fidelidade: Protótipo-de-Alta-Fidelidade.md
    - Relatório de Casos de Teste: Relatório-de-Casos-de-Teste.md
  
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

markdown_extensions:
  - codehilite
