site_name: SIGS

nav:
  - Home: index.md
  - Contribute: contribute.md
  - Stylesheet:
    - Css: stylesheet/css.md
  - Contributors: contributors.md
  
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

markdown_extensions:
  - codehilite
